mail_filter:
  subject: RTG Rekon Go-jek
  after: {{ datetime_start.timestamp()  | int }}
  before: {{ datetime_end.timestamp() | int }}
  attachment: true

file_to_extract:
  source : attachment
  file_pattern: RPT_HASIL*
  # mime_type: application/x-zip-compressed

transform:
  etl_model: rpt_cleaner
  filename_format: TM007C02_DS0059_{{ now.strftime("%y%m%d%H%M%S") }}_{file_date}_{source_file}

export_destination:
  protocol: sftp
  hostname: ftp.blackline.com
  username: sapgojek
  port: 22
  private_key: /root/.ssh/id_rsa.finrec
  dir: /SB/TEST
