image:
  name: asia.gcr.io/bi-gojek/gmail2bq-base

stages:
  - testing
  - deploy
  - scheduled

variables:
  PATH_CREDENTIAL: "/tmp/gmail2bq.id_rsa"
  ANSIBLE_HOST_KEY_CHECKING: "false"
  IMAGE_NAME: gmail2bq
  IMAGE_URL: artifactory-gojek.golabs.io:6555/${IMAGE_NAME}:latest
  tmp_dir: tmp
  export_dir: data/in

before_script:
    - mkdir -p $export_dir $tmp_dir
    - cp $GOOGLE_APPLICATION_CREDENTIALS $tmp_dir/
    - cp $GMAIL_CREDENTIAL_FILE $export_dir/credentials.json

testing:config:
  image: "python:3.8"
  stage: testing
  except:
    - schedules
  script:
    - pip install -r requirements.txt
    - python tests/config_validation.py tests/config_schema.yaml configs/



testing:unit:
  stage: testing
  except:
    - schedules
  tags:
    - docker
    - docker_artifactory
  variables:
    env : TEST_CONFIG 
  script:
    - DSTART=`date +"%Y-%m-%d" -d "-1 day" `
    - echo "GMAIL_TOKEN_FILE='${GMAIL_TOKEN_FILE}'" > app.env
    - echo "CONFIG_DIRPATH=${CONFIG_DIRPATH}" >> app.env
    - cp configs/${CONFIG_DIRPATH}/* $export_dir
    - docker build  --no-cache -t artifactory-gojek.golabs.io:6555/${IMAGE_NAME}:tests -f $( pwd )/tests/Dockerfile . 
    - docker run  -v `pwd`/$export_dir:/$export_dir  -v `pwd`/$tmp_dir:/$tmp_dir -e export_dir=/$export_dir -e GOOGLE_APPLICATION_CREDENTIALS=/tmp/GOOGLE_APPLICATION_CREDENTIALS artifactory-gojek.golabs.io:6555/${IMAGE_NAME}:tests /$export_dir/config.yaml -s $DSTART

# testing: library:
#   stage: testing
#   script:
#     - tests/test-check-email.sh
#     - tests/test-extractor.sh
#     - tests/test-etls.sh
#     - tests/test-delivery.sh

build:docker:  
  image: docker:latest
  stage: deploy
  services:
    - docker:18.09.7-dind
  # variables:
  #   DOCKER_HOST: tcp://docker:2375/
  #   DOCKER_DRIVER: overlay2
  tags:
    - docker
    - docker_artifactory
    # - dind
  variables:
    tmp_dir: tmp
    export_dir: data/in
  script:
    - echo "GMAIL_TOKEN_FILE='${GMAIL_TOKEN_FILE}'" > app.env
    - docker build  --no-cache -t $IMAGE_URL -f $( pwd )/Dockerfile . 
    - docker push $IMAGE_URL

  only:
    - master
  except:
    - schedules

run_schedules:
  tags:
    - docker
    - docker_artifactory
  image:
    name: artifactory-gojek.golabs.io:6555/${IMAGE_NAME}:latest
  only:
    - schedules
  stage: scheduled
  script:
    - cp ${CONFIG_DIRPATH}/* $export_dir/
    - DSTART=`date +"%Y-%m-%d" -d "-1 day" `
    - docker run -v `pwd`/$export_dir:/$export_dir  -e env:TEST_CONFIG -v `pwd`/$tmp_dir:/$tmp_dir -e export_dir=/$export_dir -e GOOGLE_APPLICATION_CREDENTIALS=/$tmp_dir/GOOGLE_APPLICATION_CREDENTIALS -e DSTART=$DSTART $IMAGE_URL /$export_dir/config.yaml -s $DSTART
