image:
  name: asia.gcr.io/bi-gojek/gmail2bq-base

stages:
  - testing
  - deploy
  - scheduled

variables:
  PATH_CREDENTIAL: "/tmp/gmail2bq.id_rsa"
  ANSIBLE_HOST_KEY_CHECKING: "false"
  IMAGE_NAME: gmail2bq
  IMAGE_URL: artifactory-gojek.golabs.io:6555/entbi-${IMAGE_NAME}:latest
  IMAGE_URL_WITH_TAG: artifactory-gojek.golabs.io:6555/entbi-${IMAGE_NAME}:${CI_COMMIT_TAG:1}
  tmp_dir: tmp
  export_dir: data/in

before_script:
  #  - mkdir -p $export_dir $tmp_dir
#    - cp $GOOGLE_APPLICATION_CREDENTIALS $tmp_dir/
 #   - cp $GMAIL_CREDENTIAL_FILE $tmp_dir/credentials.json

testing:config:
  image: "python:3.8"
  stage: testing
  except:
    - schedules
  script:
    - pip install -r requirements.txt
    - python tests/config_validation.py tests/config_schema.yaml configs/


testing:unit:
  stage: testing
  except:
    - schedules
  tags:
    - docker
    - docker_artifactory
  variables:
    env : TEST_CONFIG 
  script:
    - DSTART=`date +"%Y-%m-%d" -d "-1 day" `
    - DEND=`date +"%Y-%m-%d" -d "$DSTART + 1 day" ` 
    - echo "export GMAIL_TOKEN_FILE='${GMAIL_TOKEN_FILE}'" >> .app.conf
    - echo "export CONFIG_DIRPATH=${CONFIG_DIRPATH}" >> .app.conf
    - docker build  --no-cache  -t artifactory-gojek.golabs.io:6555/${IMAGE_NAME}:tests -f $( pwd )/tests/Dockerfile . 
    - docker run --mount $GOOGLE_APPLICATION_CREDENTIALS=/tmp/GOOGLE_APPLICATION_CREDENTIALS -v `pwd`/${CONFIG_DIRPATH}:/$export_dir  -e export_dir=/$export_dir -e env=TEST_CONFIG -e GOOGLE_APPLICATION_CREDENTIALS=/tmp/GOOGLE_APPLICATION_CREDENTIALS artifactory-gojek.golabs.io:6555/${IMAGE_NAME}:tests /$export_dir/config.yaml -s $DSTART -e $DEND

build:docker:  
  image: docker:latest
  stage: deploy
  services:
    - docker:18.09.7-dind
  # variables:
  #   DOCKER_HOST: tcp://docker:2375/
  #   DOCKER_DRIVER: overlay2
  tags:
    - docker
    - docker_artifactory
    # - dind
  variables:
    tmp_dir: tmp
    export_dir: data/in
  script:
    - echo "export GOOGLE_APPLICATION_CREDENTIALS=/tmp/GOOGLE_APPLICATION_CREDENTIALS" >> .app.conf
    - echo "export GMAIL_TOKEN_FILE='${GMAIL_TOKEN_FILE}'" >> .app.conf
    - docker build  --no-cache -t ${IMAGE_URL} -f $( pwd )/Dockerfile . 
    - docker push ${IMAGE_URL}
  except:
    - schedules

build:tagged:  
  image: docker:latest
  stage: deploy
  services:
    - docker:18.09.7-dind
  # variables:
  #   DOCKER_HOST: tcp://docker:2375/
  #   DOCKER_DRIVER: overlay2
  tags:
    - docker
    - docker_artifactory
    # - dind
  variables:
    tmp_dir: tmp
    export_dir: data/in
  script:
    - echo "export GOOGLE_APPLICATION_CREDENTIALS=/tmp/GOOGLE_APPLICATION_CREDENTIALS" >> .app.conf
    - echo "export GMAIL_TOKEN_FILE='${GMAIL_TOKEN_FILE}'" >> .app.conf
    - docker build  --no-cache -t ${IMAGE_URL} -t ${IMAGE_URL_WITH_TAG} -f $( pwd )/Dockerfile . 
    - docker push ${IMAGE_URL}
    - docker push ${IMAGE_URL_WITH_TAG}
  only:
    variables:
      - $CI_COMMIT_TAG =~ /^v.*$/
  except:
    - schedules

run_schedules:
  tags:
    - docker
    - docker_artifactory
  image:
    name: artifactory-gojek.golabs.io:6555/entbi-${IMAGE_NAME}:latest
  only:
    - schedules
  stage: scheduled
  # variables:
  #   - DSTART:`date +"%Y-%m-%d" -d "$delta_day day" ` 
  #   - DEND: `date +"%Y-%m-%d" +d "$DSTAR 1 day" ` 
  script:
    # - cp ${CONFIG_DIRPATH}/* $export_dir/
    - DSTART=`date +"%Y-%m-%d" -d "$delta_day day" ` 
    - DEND=`date +"%Y-%m-%d" -d "$DSTART + 1 day" `
    # - bin/gmail2bq -s $DSTART $CONFIG_DIRPATH 
    - docker run --mount $GOOGLE_APPLICATION_CREDENTIALS=/tmp/GOOGLE_APPLICATION_CREDENTIALS -v `pwd`/${CONFIG_DIRPATH}:/$export_dir  -e env:TEST_CONFIG -e TMP_DIR=/data/out $IMAGE_URL /$export_dir/config.yaml -s $DSTART
