image:
  name: asia.gcr.io/bi-gojek/gmail2bq-base

stages:
  - testing
  - deploy
  - scheduled

variables:
  PATH_CREDENTIAL: "/tmp/gmail2bq.id_rsa"
  ANSIBLE_HOST_KEY_CHECKING: "false"
  IMAGE_NAME: gmail2bq
  IMAGE_URL: artifactory-gojek.golabs.io:6555/entbi-${IMAGE_NAME}:latest
  IMAGE_URL_WITH_TAG: artifactory-gojek.golabs.io:6555/entbi-${IMAGE_NAME}:${CI_COMMIT_TAG:1}
  tmp_dir: tmp
  export_dir: data/in

# before_script:
#   - mkdir -p $export_dir $tmp_dir
#   - cp $GOOGLE_APPLICATION_CREDENTIALS $tmp_dir/
#   - cp $GMAIL_CREDENTIAL_FILE $tmp_dir/credentials.json

testing:config:
  image: "python:3.8"
  stage: testing
  except:
    - schedules
  script:
    - pip install -qr requirements.txt
    - python tests/config_validation.py tests/config_schema.yaml configs/


testing:unit:
  stage: testing
  except:
    - schedules
  tags:
    - docker
    - docker_artifactory
  variables:
    env : TEST_CONFIG 
  script:
    - DSTART=`date +"%Y-%m-%d" -d "-1 day" `
    - DEND=`date +"%Y-%m-%d" -d "$DSTART + 1 day" ` 
    - echo "BQ_SERVICE_ACCOUNT=$BQ_SERVICE_ACCOUNT" >> .app.conf	
    - docker build  --no-cache  -t artifactory-gojek.golabs.io:6555/${IMAGE_NAME}:tests -f $( pwd )/tests/Dockerfile . 
    - docker run --env-file .app.conf -v `pwd`/${CONFIG_DIRPATH}:/$export_dir --mount type=bind,source=$GMAIL_TOKEN_FILE,target=/data/in/token.json -e env='TEST_CONFIG' artifactory-gojek.golabs.io:6555/${IMAGE_NAME}:tests /$export_dir/config.yaml -s $DSTART -e $DEND

build:docker:  
  image: docker:latest
  stage: deploy
  services:
    - docker:18.09.7-dind
  # variables:
  #   DOCKER_HOST: tcp://docker:2375/
  #   DOCKER_DRIVER: overlay2
  tags:
    - docker
    - docker_artifactory
    # - dind
  variables:
    tmp_dir: tmp
    export_dir: data/in
  script:
    - docker build  --no-cache -t ${IMAGE_URL} -f $( pwd )/Dockerfile . 
    - docker push ${IMAGE_URL}
  only:
    - master
  except:
    - schedules

build:tagged:  
  image: docker:latest
  stage: deploy
  services:
    - docker:18.09.7-dind
  # variables:
  #   DOCKER_HOST: tcp://docker:2375/
  #   DOCKER_DRIVER: overlay2
  tags:
    - docker
    - docker_artifactory
    # - dind
  variables:
    tmp_dir: tmp
    export_dir: data/in
  script:
    - docker build  --no-cache -t artifactory-gojek.golabs.io:6555/entbi-${IMAGE_NAME}:${CI_COMMIT_TAG:1} -f $( pwd )/Dockerfile . 
    - docker push artifactory-gojek.golabs.io:6555/entbi-${IMAGE_NAME}:${CI_COMMIT_TAG:1}
    - docker tag artifactory-gojek.golabs.io:6555/entbi-${IMAGE_NAME}:${CI_COMMIT_TAG:1} artifactory-gojek.golabs.io:6555/entbi-${IMAGE_NAME}:latest
    - docker push artifactory-gojek.golabs.io:6555/entbi-${IMAGE_NAME}:latest
  only:
    variables:
      - $CI_COMMIT_TAG =~ /^v.*$/
  except:
    - schedules

run_schedules:
  image:
    name: $IMAGE_URL
  only:
    - schedules
  stage: scheduled
  variables:
    GOOGLE_APPLICATION_CREDENTIALS: /root/gcloud-credential.json
  before_script:
    - ls /opt/gmail2bq || true
    - echo "$BQ_SERVICE_ACCOUNT" > $GOOGLE_APPLICATION_CREDENTIALS
  script:
    - /opt/gmail2bq/bin/gmail2bq  /$export_dir/config.yaml -s `date +"%Y-%m-%d" -d "$delta_day day" `
  #   - docker run --env-file .app.conf -v `pwd`/${CONFIG_DIRPATH}:/$export_dir --mount type=bind,source=$GMAIL_TOKEN_FILE,target=/data/in/token.json --mount type=bind,source=$GOOGLE_APPLICATION_CREDENTIALS,target=/tmp/GOOGLE_APPLICATION_CREDENTIALS -e env:TEST_CONFIG   $IMAGE_URL /$export_dir/config.yaml -s `date +"%Y-%m-%d" -d "$delta_day day" ` 
