mail_filter:
  subject: LAPORAN TRANSAKSI DATA REKON GOJEK H+0
  after: {{ datetime_start.timestamp()  | int }}
  before: {{ datetime_end.timestamp() | int }}
  attachment: true

file_to_extract:
  source : attachment
  file_pattern: PLN *.zip
  mime_type: application/x-zip-compressed

transform:
  transform_model: excel_split_sheet
  filename_format : TM007C10_DS0014_{{ now.strftime("%y%m%d%H%M%S") }}_{source_file}

load_destination:
  protocol: sftp
  hostname: ftp.blackline.com
  username: sapgojek
  port: 22
  private_key: /root/.ssh/id_rsa.finrec
  dir: /SB/TEST
