ignore_after: 15
mail_filter:
  from: no-reply@go-pay.co.id
  subject: '[ARS][PROD] BILL MKM Report'
  after: {{ datetime_start.timestamp()  | int }}
  before: {{ datetime_end.timestamp()  | int }}
  
file_to_extract:
  source : url_in_body
  url_xpath: //td/a[contains(text(),'txt')]

file_etl:
  etl_model: mkm_remove_version
  filename_format: TM007C00_DS0012_{{now.strftime('%y%m%d%H%M%S')}}_{file_date}_{source_file}


export_destination:
  protocol: sftp
  hostname: ftp.blackline.com
  username: sapgojek
  port: 22
  private_key: /root/.ssh/id_rsa.finrec
  dir: /SB/TEST
