mail_filter:
  # from: wallstreet@midtrans.com
  subject: 'BQ vs Wallstreet Result: Discrepancy Found for checking time'
  after: {{ datetime_start.timestamp()  | int }}
  before: {{ datetime_end.timestamp()  | int }}

file_to_extract:
  source : body
  mime_type: 'text/html'
  # url_xpath: //a[text()='here']
  # password_xpath: "//strong"

transform:
  transform_model: parse_email_body
  filename_format: WALLSTREET_UNMATCH_{{ datetime_start.strftime("%Y%m%d") }}

load_destination: []
#   protocol: sftp
#   hostname: ftp.blackline.com
#   username: sapgojek
#   port: 22
#   private_key: /root/.ssh/id_rsa.finrec
#   dir: /SB/TEST

ignore_after: 2
