mail_filter:
  subject: LAPORAN TRANSAKSI PEMBAYARAN BPJS
  after: {{ datetime_start.timestamp()  | int }}
  before: {{ datetime_end.timestamp() | int }}

file_to_extract:
  source : attachment
  file_pattern: PT*RPT.zip
  mime_type: application/x-zip-compressed

transform:
  etl_model: rpt_cleaner
  filename_format: TM007C01_DS0059_{{ now.strftime("%y%m%d%H%M%S") }}_{source_file}

export_destination:
  protocol: sftp
  hostname: ftp.blackline.com
  username: sapgojek
  port: 22
  private_key: /root/.ssh/id_rsa.finrec
  dir: /SB/TEST
