mail_filter:
  from: coupa.com
  subject: "*Vendor Post Screening"
  attachment: true
  after: {{ (datetime_start + timedelta(hours=7) ).timestamp()  | int }}
  before: {{ (datetime_end  + timedelta(hours=7) ).timestamp()  | int  }}

file_to_extract:
  source : attachment
  file_pattern: "Vendor_Post_Screening*.zip"

transform:
  transform_model: unzip
  filename_format : coupa_post_screening_{{ datetime_start.strftime("%Y%m%d") }}_{source_file}

load_destination:
  protocol: gcs
  bucket: access_sap_bq
  dir: coupa/vendor_screening/{{ datetime_start.strftime("%Y%m%d") }}/
  
  # table_id: data-gojek-id-raw-internal.enterprise_platform.coupa_esg_order
  # schema: schema.json
  # load_method: replace
  # field_delimiter: tab 
  # skip_leading_rows: 1
  # partition: {{ datetime_start.strftime("%Y%m%d")}}

