mail_filter:
  from: autonotification@concursolutions.com
  subject: "*ESG Report v2_Request"
  attachment: true

file_to_extract:
  source : attachment
  file_pattern: "*ESG Report v2_Request.csv"

file_etl:
  filename_format : concur_integration_{{ now.strftime("%Y%m%d") }}_{source_file}

export_destination:
  protocol: gcs
  bucket: access_sap_bq
  dir: ocean/data-gojek-id-raw-internal/enterprise_platform/concur_integration_request
