mail_filter:
  from: novan.firmansyah@gotocompany.com
  subject: drive test
  after: {{ datetime_start.timestamp()  | int }}
  before: {{ datetime_end.timestamp()  | int }}
  # attachment: true

file_to_extract:
  source : url_in_body
  url_xpath: //a[text()='link to file']
  

transform:
  filename_format: GDRIVE_{{ now.strftime("%y%m%d%H%M%S") }}.html

load_destination:
#   protocol: sftp
#   hostname: ftp.blackline.com
#   username: sapgojek
#   port: 22
#   private_key: /root/.ssh/id_rsa.finrec
#   dir: /SB/TEST
