mail_filter:
  from: wallstreet@midtrans.com
  subject: Transaction share csv download
  after: {{ datetime_start.timestamp()  | int }}
  before: {{ datetime_end.timestamp()  | int }}

file_to_extract:
  source : url_in_body
  url_xpath: //a[text()='here']
  password_xpath: "//strong"

transform:
  filename_format: WALLSTREET_{{ now.strftime("%y%m%d%H%M%S") }}

export_destination:
  protocol: sftp
  hostname: ftp.blackline.com
  username: sapgojek
  port: 22
  private_key: /root/.ssh/id_rsa.finrec
  dir: /SB/TEST
