mail_filter:
  from: coupa.com
  subject: "*Sustainability ESG Report"
  attachment: true
  after: {{ (datetime_start - timedelta(hours=7)).timestamp()  | int }}
  before: {{ (datetime_end - timedelta(hours=7)).timestamp()  | int  }}

file_to_extract:
  source : attachment
  file_pattern: "*Sustainability_ESG_Report_*.xlsx"

transform:
  transform_model: xlsx2csv
  filename_format : coupa_sustainability_{{ now.strftime("%Y%m%d") }}_{source_file}

load_destination:
  protocol: gcs
  bucket: integration_exchange
  dir: workato/ocean/data-gojek-id-raw-internal/enterprise_platform/coupa_esg_purchase_of_goods_and_services
