mail_filter:
  from: concursolutions.com
  subject: "Report: ESG Report_Daily Ground Transportation Scheduled"
  attachment: true
  after: {{ (datetime_start + timedelta(hours=7) ).timestamp()  | int }}
  before: {{ (datetime_end  + timedelta(hours=7) ).timestamp()  | int  }}

file_to_extract:
  source : attachment
  file_pattern: "*Scheduled.csv"

transform:
  filename_format : ESGDUMP_{{ datetime_start.strftime("%Y%m%d") }}_{source_file}

load_destination:
  - protocol: gcs
    bucket: integration_exchange
    dir: workato/ocean/data-gojek-id-raw-internal/enterprise_platform/Daily_Ground_Transportation
