mail_filter:
  subject: Daily Sales Report Google Play
  after: {{ datetime_start.timestamp()  | int }}
  before: {{ datetime_end.timestamp() | int }}
  attachment: true

file_to_extract:
  source : attachment
  file_pattern: BHN_Go*
  # mime_type: application/x-zip-compressed

transform:
  filename_format: TM007C03_DS0054_{{now.strftime("%y%m%d%H%M%S")}}_{source_file}

export_destination:
  protocol: sftp
  hostname: ftp.blackline.com
  username: sapgojek
  port: 22
  private_key: /root/.ssh/id_rsa.finrec
  dir: /SB/TEST
